// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"
	"database/sql"
)

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO templates (name, empty_yaml, file)
VALUES (?, ?, ?)
RETURNING id
`

type CreateTemplateParams struct {
	Name      string
	EmptyYaml sql.NullString
	File      sql.NullString
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createTemplate, arg.Name, arg.EmptyYaml, arg.File)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteCustomFieldsByTemplateID = `-- name: DeleteCustomFieldsByTemplateID :exec
DELETE FROM custom_fields
WHERE template_id = ?
`

func (q *Queries) DeleteCustomFieldsByTemplateID(ctx context.Context, templateID int64) error {
	_, err := q.db.ExecContext(ctx, deleteCustomFieldsByTemplateID, templateID)
	return err
}

const deleteEntriesByTemplateID = `-- name: DeleteEntriesByTemplateID :exec
DELETE FROM entries
WHERE template_id = ?
`

func (q *Queries) DeleteEntriesByTemplateID(ctx context.Context, templateID int64) error {
	_, err := q.db.ExecContext(ctx, deleteEntriesByTemplateID, templateID)
	return err
}

const deleteEntryByPath = `-- name: DeleteEntryByPath :exec
DELETE FROM entries
WHERE path = ?
`

func (q *Queries) DeleteEntryByPath(ctx context.Context, path string) error {
	_, err := q.db.ExecContext(ctx, deleteEntryByPath, path)
	return err
}

const deletePdfNameSchemaByTemplateID = `-- name: DeletePdfNameSchemaByTemplateID :exec
DELETE FROM pdf_name_schema
WHERE template_id = ?
`

func (q *Queries) DeletePdfNameSchemaByTemplateID(ctx context.Context, templateID int64) error {
	_, err := q.db.ExecContext(ctx, deletePdfNameSchemaByTemplateID, templateID)
	return err
}

const deleteTabDescSchemaByTemplateID = `-- name: DeleteTabDescSchemaByTemplateID :exec
DELETE FROM tab_desc_schema
WHERE template_id = ?
`

func (q *Queries) DeleteTabDescSchemaByTemplateID(ctx context.Context, templateID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTabDescSchemaByTemplateID, templateID)
	return err
}

const deleteTemplateByID = `-- name: DeleteTemplateByID :exec
DELETE FROM templates
WHERE id = ?
`

func (q *Queries) DeleteTemplateByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTemplateByID, id)
	return err
}

const doesPathExist = `-- name: DoesPathExist :one
SELECT path
FROM entries
WHERE path = ?
`

func (q *Queries) DoesPathExist(ctx context.Context, path string) (string, error) {
	row := q.db.QueryRowContext(ctx, doesPathExist, path)
	err := row.Scan(&path)
	return path, err
}

const getAllEntries = `-- name: GetAllEntries :many
SELECT id, template_id, data, path, yaml, date
FROM entries
`

func (q *Queries) GetAllEntries(ctx context.Context) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, getAllEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.Data,
			&i.Path,
			&i.Yaml,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllEntriesPlusTemplateName = `-- name: GetAllEntriesPlusTemplateName :many
SELECT
    entries.id,
    entries.data,
    entries.path,
    entries.yaml,
    entries.date,
    templates.name AS template_name
FROM entries
JOIN templates ON entries.template_id = templates.id
ORDER BY entries.date DESC
`

type GetAllEntriesPlusTemplateNameRow struct {
	ID           int64
	Data         string
	Path         string
	Yaml         sql.NullString
	Date         sql.NullInt64
	TemplateName string
}

func (q *Queries) GetAllEntriesPlusTemplateName(ctx context.Context) ([]GetAllEntriesPlusTemplateNameRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllEntriesPlusTemplateName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllEntriesPlusTemplateNameRow
	for rows.Next() {
		var i GetAllEntriesPlusTemplateNameRow
		if err := rows.Scan(
			&i.ID,
			&i.Data,
			&i.Path,
			&i.Yaml,
			&i.Date,
			&i.TemplateName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTemplates = `-- name: GetAllTemplates :many
SELECT id, name, empty_yaml, file
FROM templates
`

func (q *Queries) GetAllTemplates(ctx context.Context) ([]Template, error) {
	rows, err := q.db.QueryContext(ctx, getAllTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EmptyYaml,
			&i.File,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustomFieldsByTemplateName = `-- name: GetCustomFieldsByTemplateName :many
SELECT cf.id, cf.template_id, cf.key, cf.desc
FROM custom_fields cf
JOIN templates t ON cf.template_id = t.id
WHERE t.name = ?
`

func (q *Queries) GetCustomFieldsByTemplateName(ctx context.Context, name string) ([]CustomField, error) {
	rows, err := q.db.QueryContext(ctx, getCustomFieldsByTemplateName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomField
	for rows.Next() {
		var i CustomField
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.Key,
			&i.Desc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntryByPath = `-- name: GetEntryByPath :one
SELECT id, template_id, data, path, yaml, date
FROM entries
WHERE path = ?
`

func (q *Queries) GetEntryByPath(ctx context.Context, path string) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntryByPath, path)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.Data,
		&i.Path,
		&i.Yaml,
		&i.Date,
	)
	return i, err
}

const getPdfNamingByTemplateID = `-- name: GetPdfNamingByTemplateID :many
SELECT id, template_id, value
FROM pdf_name_schema
WHERE template_id = ?
`

func (q *Queries) GetPdfNamingByTemplateID(ctx context.Context, templateID int64) ([]PdfNameSchema, error) {
	rows, err := q.db.QueryContext(ctx, getPdfNamingByTemplateID, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PdfNameSchema
	for rows.Next() {
		var i PdfNameSchema
		if err := rows.Scan(&i.ID, &i.TemplateID, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTabDescriptionsByTemplateID = `-- name: GetTabDescriptionsByTemplateID :many
SELECT id, template_id, value
FROM tab_desc_schema
WHERE template_id = ?
`

func (q *Queries) GetTabDescriptionsByTemplateID(ctx context.Context, templateID int64) ([]TabDescSchema, error) {
	rows, err := q.db.QueryContext(ctx, getTabDescriptionsByTemplateID, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TabDescSchema
	for rows.Next() {
		var i TabDescSchema
		if err := rows.Scan(&i.ID, &i.TemplateID, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTemplateByName = `-- name: GetTemplateByName :one
SELECT id, name, empty_yaml, file
FROM templates
WHERE name = ?
`

func (q *Queries) GetTemplateByName(ctx context.Context, name string) (Template, error) {
	row := q.db.QueryRowContext(ctx, getTemplateByName, name)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EmptyYaml,
		&i.File,
	)
	return i, err
}

const insertCustomField = `-- name: InsertCustomField :exec
INSERT INTO custom_fields (template_id, key, desc)
VALUES (?, ?, ?)
`

type InsertCustomFieldParams struct {
	TemplateID int64
	Key        string
	Desc       string
}

func (q *Queries) InsertCustomField(ctx context.Context, arg InsertCustomFieldParams) error {
	_, err := q.db.ExecContext(ctx, insertCustomField, arg.TemplateID, arg.Key, arg.Desc)
	return err
}

const insertEntry = `-- name: InsertEntry :exec
INSERT INTO entries (template_id, data, path, yaml, date)
VALUES (?, ?, ?, ?, ?)
`

type InsertEntryParams struct {
	TemplateID int64
	Data       string
	Path       string
	Yaml       sql.NullString
	Date       sql.NullInt64
}

func (q *Queries) InsertEntry(ctx context.Context, arg InsertEntryParams) error {
	_, err := q.db.ExecContext(ctx, insertEntry,
		arg.TemplateID,
		arg.Data,
		arg.Path,
		arg.Yaml,
		arg.Date,
	)
	return err
}

const insertPdfNameSchema = `-- name: InsertPdfNameSchema :exec
INSERT INTO pdf_name_schema (template_id, value)
VALUES (?, ?)
`

type InsertPdfNameSchemaParams struct {
	TemplateID int64
	Value      string
}

func (q *Queries) InsertPdfNameSchema(ctx context.Context, arg InsertPdfNameSchemaParams) error {
	_, err := q.db.ExecContext(ctx, insertPdfNameSchema, arg.TemplateID, arg.Value)
	return err
}

const insertTabDescSchema = `-- name: InsertTabDescSchema :exec
INSERT INTO tab_desc_schema (template_id, value)
VALUES (?, ?)
`

type InsertTabDescSchemaParams struct {
	TemplateID int64
	Value      string
}

func (q *Queries) InsertTabDescSchema(ctx context.Context, arg InsertTabDescSchemaParams) error {
	_, err := q.db.ExecContext(ctx, insertTabDescSchema, arg.TemplateID, arg.Value)
	return err
}

const updateDataById = `-- name: UpdateDataById :exec
UPDATE entries
SET data = ?
WHERE id = ?
`

type UpdateDataByIdParams struct {
	Data string
	ID   int64
}

func (q *Queries) UpdateDataById(ctx context.Context, arg UpdateDataByIdParams) error {
	_, err := q.db.ExecContext(ctx, updateDataById, arg.Data, arg.ID)
	return err
}

const updateYamlById = `-- name: UpdateYamlById :exec
UPDATE entries
SET yaml = ?
WHERE id = ?
`

type UpdateYamlByIdParams struct {
	Yaml sql.NullString
	ID   int64
}

func (q *Queries) UpdateYamlById(ctx context.Context, arg UpdateYamlByIdParams) error {
	_, err := q.db.ExecContext(ctx, updateYamlById, arg.Yaml, arg.ID)
	return err
}

const updateYamlByPath = `-- name: UpdateYamlByPath :exec
UPDATE entries
SET yaml = ?
WHERE path = ?
`

type UpdateYamlByPathParams struct {
	Yaml sql.NullString
	Path string
}

func (q *Queries) UpdateYamlByPath(ctx context.Context, arg UpdateYamlByPathParams) error {
	_, err := q.db.ExecContext(ctx, updateYamlByPath, arg.Yaml, arg.Path)
	return err
}
