- task: "Gerät in KME-Portal prüfen (ggf. Tag hinzufügen, z.B.: Mitte, STS)"
  checked: false
- task: "Gerät inventarisieren (Inventar-Nummer ankleben)"
  checked: false
- task: "Gerät in Datomo anlegen"
  checked: false
  children:
    - task: "IMEI und User eintragen"
      checked: false
    - task: "Beschreibung eintragen, z.B.: TF Mitte Halle"
      checked: false
    - task: "Custom Fields ausfüllen (KCC-Enrollment Token, Standort (Meldestelle), Gerätekennwort (6-stelliger PIN), Inventarnummer)"
      checked: false
- task: "Gerät installieren"
  checked: false
  children:
    - task: "Bestätigen von Knox Richtlinien"
      checked: false
    - task: "MDM Accessibility aktivieren"
      checked: false
    - task: "Zufällige 6-stellige PIN aus dem Custom Field entnehmen und eintragen"
      checked: false
    - task: "Bildschirm-Timeout einstellen (auf Maximum)"
      checked: false
    - task: "Datum und Uhrzeit einstellen"
      checked: false
- task: "Alle Applikationen öffnen und Freigaben bestätigen"
  checked: false
  children:
    - task: "Diloc einrichten (TF/KB Tablet)"
      checked: false
    - task: "Inline FAS Einrichten und freigeben (TF Handy)"
      checked: false
    - task: "Inline Info Einrichten und freigeben (KB Tablet)"
      checked: false
    - task: "Adobe Werbung wegklicken"
      checked: false
    - task: "Teamviewer Quicksupport Remote-Control-Feature aktivieren"
      checked: false
    - task: "KNOX E-FOTA bereitstellen und ausführen"
      checked: false
- task: "IMEI an KNOX E-FOTA Experten übergeben und auf Rückmeldung warten"
  checked: false
- task: "Wenn möglich: Exchange-Konto Konfiguration abschließen"
  checked: false
- task: "Überprüfung SIM-Karte im Vodafone-Portal (via Rufnummer)"
  checked: false
  children:
    - task: "Rufnummer des Nutzers suchen"
      checked: false
      children:
        - task: "Altes System Plugin? Blanko-Karte im MDM anlegen"
          checked: false
        - task: "Neues System Plugin? Blanko-Karte im MDM anlegen"
          checked: false
        - task: "Altes System Triple? Karte aus dem System übernehmen"
          checked: false
        - task: "Neues System Triple? Übertragen ins Gerät"
          checked: false
- task: "SIM-Karte in Datomo anlegen und dem Gerät zuweisen"
  checked: false
  children:
    - task: "Bei Tablets überprüfen, ob Ultracard bereits vorhanden ist"
      checked: false
    - task: "Handys/Tablets im cda-Portal auf cda/cda5 überprüfen"
      checked: false
    - task: "Bei neuen Nutzern, Nummer im AD hinterlegen"
      checked: false
- task: "Gerät reinigen und verpacken"
  checked: false
  children:
    - task: "Ladegeräte beilegen"
      checked: false
    - task: "SIM-Karten-Nadel beilegen"
      checked: false
    - task: "Ausgabe-/und Rückgabeprotokoll ausdrucken und beilegen (im datomo ausdrucken)"
      checked: false
    - task: "SIM-Karten einlegen oder beilegen"
      checked: false
    - task: "SIM-Karten-Zettel bereitlegen"
      checked: false
      children:
        - task: "Bei neuer Triple-SIM => Aktivierungszettel"
          checked: false
        - task: "Bei schon vorhandener Triple-SIM => Tauschzettel"
          checked: false
        - task: "Bei Buchung einer Ultracard => Fertigzettel"
          checked: false
- task: "Gerät abgeben (bei Gebietsleiter oder in Person)"
  checked: false
  children:
    - task: "Ticket pausieren und an 'Ruecklaufer' weiterleiten"
      checked: false
    - task: "Gerät inventarisieren"
      checked: false
- task: "Dieses Dokument ablegen unter O:/Organisation/IT/Workplace/02_Dokumentation/27_Laufzettel MDM"
  checked: false

