- task: "Gerät wurde im KME-Portal überprüft (ggf. Tag hinzufügen, z.B.: Mitte, STS)"
  checked: false
- task: "Gerät wurde inventarisiert (Inventar-Nummer ankleben)."
  checked: false
- task: "Gerät wurde im datomo anlegen."
  checked: false
  children:
    - task: "IMEI und User eintragen."
      checked: false
    - task: "Beschreibung eintragen, z.B.: TF Mitte Halle"
      checked: false
    - task: "Custom Fields wurden ausgefüllt (KCC-Enrollment Token, Standort (Meldestelle), Gerätekennwort (6-stelliger PIN), Inventarnummer)"
      checked: false
- task: "Basis Installation des Geräts wurde durchgeführt"
  checked: false
  children:
    - task: "Knox Richtlinien bestätigen"
      checked: false
    - task: "MDM Accessibility aktivieren."
      checked: false
    - task: "Zufällige 6-stellige PIN aus dem Custom Field entnehmen und eintragen."
      checked: false
    - task: "Bildschirm-Timeout einstellen (auf Maximum)."
      checked: false
    - task: "Datum und Uhrzeit einstellen."
      checked: false
- task: "Folgende Anwendungen sind installiert, konfiguriert und ausführbar:"
  checked: false
  children:
    - task: "DiLoc (TF/KB Tablet)"
      checked: false
      children:
        - task: Synchronisation angestoßen
          checked: false
    - task: "Inline Info (KB Tablet)"
      checked: false
    - task: "Inline FAS (TF Handy)"
      checked: false
    - task: "IVU (Tablet und Handy)"
      checked: false
    - task: "Adobe Acrobat"
      checked: false
    - task: "Teamviewer Quicksupport"
      checked: false
    - task: "KNOX E-FOTA"
      checked: false
    - task: "E-Mails/Adressbuch (Exchange-Konto)"
      checked: false
- task: "IMEI wurde an KNOX E-FOTA Experten übergeben (IMEI, Job, Modell)."
  checked: false
  children:
    - task: "Gerät ist schon Mitglied einer Kampagne."
      checked: false
- task: "Rufnummer wurde im Vodafone-Portal überprüft und im datomo als SIM-Karte angelegt."
  checked: false
- task: "Rufnummer wurde dem CDA/CDA5 hinzugefügt."
  checked: false
- task: "CDA-Zugangspunkt wurde mithilfe der Richtlinie ausgerollt und auf dem Gerät geprüft."
  checked: false
- task: "SIM-Karte wurde durch einlegen ins Gerät getestet."
  checked: false
  children:
    - task: "Nicht möglich, da SIM-Tausch."
      checked: false
- task: "Gerät wurde gereinigt und mit folgenden Gegenständen verpackt:"
  checked: false
  children:
    - task: "Ladegerät"
      checked: false
    - task: "SIM-Karten-Nadel"
      checked: false
    - task: "SIM-Karte (bei SIM-Tausch)"
      checked: false
    - task: "Ausgabe-/und Rückgabeprotokoll"
      checked: false
    - task: "SIM-Karten-Info-Zettel"
      checked: false
      children:
        - task: "Bei neuer Triple-SIM => Aktivierungszettel"
          checked: false
        - task: "Bei schon vorhandener Triple-SIM => Tauschzettel"
          checked: false
        - task: "Bei Buchung einer Ultracard => Fertigzettel"
          checked: false
- task: "Gerät abgeben (bei Gebietsleiter oder in Person)"
  checked: false
  children:
    - task: "Ticket pausieren und an 'Ruecklaufer' weiterleiten"
      checked: false
    - task: "Gerät inventarisieren"
      checked: false
