// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type CustomField struct {
	ID         int64
	TemplateID int64
	Key        string
	Desc       string
}

type Entry struct {
	ID         int64
	TemplateID int64
	Data       string
	Path       string
	Yaml       sql.NullString
	Date       sql.NullInt64
}

type PdfNameSchema struct {
	ID         int64
	TemplateID int64
	Value      string
}

type TabDescSchema struct {
	ID         int64
	TemplateID int64
	Value      string
}

type Template struct {
	ID        int64
	Name      string
	EmptyYaml sql.NullString
	File      sql.NullString
}
